name: Report bug
title: "[Bug Report]: "
description: Report a bug in the application
labels: "bug"
body:
  - type: dropdown
    id: bug_type
    attributes:
      label: 问题类型
      description: 请选择问题类型
      options:
        - 网站内容
        - 网站功能
        - 游戏下载
        - 其他
    validations:
      required: true
  - type: textarea
    id: bug_description
    attributes:
      label: 问题描述
      description: 描述一下你遇到的问题
    validations:
      required: true
  - type: textarea
    id: bug_screenshot
    attributes:
      label: 问题截图（可选）
      description: 请提供问题截图
    validations:
      required: false
  - type: input
    id: bug_link
    attributes:
      label: 问题链接（可选）
      description: 请提供问题链接
    validations:
      required: false