name: Request feature
title: "[Feature Request]: "
description: Request a feature in the application
labels: ["feature"]
body:
  - type: dropdown
    id: feature_type
    attributes:
      label: 功能类型
      description: 请选择功能类型
      options:
        - 网站功能
        - 游戏下载
        - 其他
    validations:
      required: true
  - type: textarea
    id: feature_description
    attributes:
      label: 功能描述
      description: 简单描述一下你想要的功能
    validations:
      required: true
  - type: textarea
    id: implementation_idea
    attributes:
      label: 实现思路（可选）
      description: 你有什么实现这个功能的思路吗？
    validations:
      required: false