name: Issue to Markdown PR

env:
  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
  WEBDAV_USERNAME: ${{ secrets.WEBDAV_USERNAME }}
  WEBDAV_PASSWORD: ${{ secrets.WEBDAV_PASSWORD }}
  DEEPL_AUTH_KEY: ${{ secrets.DEEPL_AUTH_KEY }}
  ISSUE_NUMBER: ${{ github.event.issue.number }}

on:
  issues:
    types: [closed]

jobs:
  create-markdown-and-pr:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.x'
      
      - name: Install dependencies
        run: pip install requests deepl Jinja2 Pillow pillow_avif_plugin

      - name: Run Python script to generate Markdown
        id: generate_markdown
        run: |
          python .github/scripts/add_new_game/main.py ${{ github.event.issue.number }}


      - name: Commit Markdown file
        run: |
          git config --global user.name '${{ github.event.issue.user.login }}'
          git config --global user.email '${{ github.event.issue.user.login }}@users.noreply.github.com'
          git add .
          git commit -m "Add Markdown file for closed Issue #${{ github.event.issue.number }}"

      - name: Create Pull Request
        uses: peter-evans/create-pull-request@v3
        with:
          commit-message: "Add Markdown file for closed Issue #${{ github.event.issue.number }}"
          title: "Add Markdown file for Issue #${{ github.event.issue.number }}"
          body: "This PR adds a Markdown file generated based on the content of the closed Issue #${{ github.event.issue.number }}."
          branch: "issue-${{ github.event.issue.number }}-markdown"
